# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# TODO
# before_all do
#   ensure_git_status_clean
# end

if is_ci
  password = SecureRandom.base64
  keychain_name = "fastlane"
  ENV["MATCH_KEYCHAIN_NAME"] = keychain_name
  ENV["MATCH_KEYCHAIN_PASSWORD"] = password

  create_keychain(
    name: keychain_name,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: true,
    password: password
  )
end

platform :ios do
  desc "Deploy iOS app on the TestFlight"

  lane :deploy do
    match(type: "development", readonly: is_ci)
    match(type: "appstore", readonly: is_ci)
    ionic(
      platform: 'ios',
      prod: true,
      release: true,
      type: 'appstore',
      build_number: Time.new.strftime("%Y.%m.%d.%H.%M")
    )
    upload_to_testflight(skip_submission: true, ipa: ENV["CORDOVA_IOS_RELEASE_BUILD_PATH"])
  end
end